# Generated by Django 4.0.3 on 2022-04-11 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('type', models.CharField(choices=[('I', 'Illustrator'), ('A', 'Author'), ('T', 'Translator')], max_length=15, verbose_name='Вид деятельности')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, upload_to='media/covers/%Y/%m/%d', verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('publish_year', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Дата публикации')),
                ('pages', models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Кол-во страниц')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Название')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('downloads', models.IntegerField(verbose_name='Скачиваний')),
                ('age_restriction', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Возрастное ограничение')),
                ('type', models.CharField(choices=[('T', 'Текст'), ('A', 'Аудио'), ('D', 'Черновик')], max_length=15, verbose_name='Тип')),
                ('language', models.CharField(choices=[('RUS', 'Русский'), ('ENG', 'Английский'), ('FR', 'Французкий')], max_length=15, verbose_name='Язык')),
                ('status', models.CharField(choices=[('Published', 'Опубликована'), ('Announced', 'Анонсирована')], max_length=15, verbose_name='Статус')),
                ('authors', models.ManyToManyField(related_name='author_books', to='books.artists', verbose_name='Авторы')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('avatar', models.ImageField(blank=True, upload_to='media/avatars/%Y/%m/%d', verbose_name='Аватар')),
                ('current_books', models.ManyToManyField(related_name='+', to='books.books', verbose_name='Читает')),
                ('forsaken_books', models.ManyToManyField(related_name='+', to='books.books', verbose_name='Брошено')),
                ('planned_books', models.ManyToManyField(related_name='+', to='books.books', verbose_name='В планах')),
                ('read_books', models.ManyToManyField(related_name='+', to='books.books', verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserBookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10, verbose_name='Содержание')),
                ('up_votes', models.IntegerField(verbose_name='Голоса за')),
                ('down_votes', models.IntegerField(verbose_name='Голоса против')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.books', verbose_name='Книга')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=10, verbose_name='IP Адресс')),
                ('content', models.CharField(max_length=10, verbose_name='Содержание')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='books.books', verbose_name='Книга')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='books.commentary', verbose_name='Родитель')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.series', verbose_name='Серия'),
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.genres', verbose_name='Жанры'),
        ),
        migrations.AddField(
            model_name='books',
            name='illustrators',
            field=models.ManyToManyField(related_name='illustrator_books', to='books.artists', verbose_name='Иллюстраторы'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.companies', verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.tags', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='books',
            name='translators',
            field=models.ManyToManyField(related_name='translator_books', to='books.artists', verbose_name='Переводчики'),
        ),
    ]
