# Generated by Django 4.0.3 on 2022-04-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name': 'Автора (Иллюстратора, Переводчика)', 'verbose_name_plural': 'Авторы (Иллюстраторы, Переводчики)'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книгу', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Издателя', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитату', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серию книг', 'verbose_name_plural': 'Серии книг'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='userbookrating',
            options={'verbose_name': 'Пользовательский рейтинг', 'verbose_name_plural': 'Пользовательские рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AddField(
            model_name='series',
            name='authors',
            field=models.ManyToManyField(related_name='author_series', to='books.artists', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='artists',
            name='type',
            field=models.CharField(choices=[('I', 'Иллюстратор'), ('A', 'Автор'), ('T', 'Переводчик')], max_length=15, verbose_name='Вид деятельности'),
        ),
        migrations.AlterField(
            model_name='books',
            name='age_restriction',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Возрастное ограничение'),
        ),
        migrations.AlterField(
            model_name='books',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Скачиваний'),
        ),
        migrations.AlterField(
            model_name='books',
            name='illustrators',
            field=models.ManyToManyField(blank=True, related_name='illustrator_books', to='books.artists', verbose_name='Иллюстраторы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='books',
            name='translators',
            field=models.ManyToManyField(blank=True, related_name='translator_books', to='books.artists', verbose_name='Переводчики'),
        ),
    ]
