# Generated by Django 4.0.3 on 2022-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_artists_first_name_alter_artists_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='illustrators',
            field=models.ManyToManyField(blank=True, null=True, related_name='illustrator_books', to='books.artists', verbose_name='Иллюстраторы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='translators',
            field=models.ManyToManyField(blank=True, null=True, related_name='translator_books', to='books.artists', verbose_name='Переводчики'),
        ),
    ]
