# Generated by Django 4.0.3 on 2022-04-12 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_books_illustrators_alter_books_translators'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name': 'Автор(а), Иллюстратор(а), Переводчик(а)', 'verbose_name_plural': 'Авторы, Иллюстраторы, Переводчики'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга(у)', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Издатель(я)', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Цитата(у)', 'verbose_name_plural': 'Цитаты'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия(ю) книг', 'verbose_name_plural': 'Серии книг'},
        ),
        migrations.AddField(
            model_name='commentary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/%Y/%m/%d', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='books',
            name='illustrators',
            field=models.ManyToManyField(blank=True, related_name='illustrator_books', to='books.artists', verbose_name='Иллюстраторы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='translators',
            field=models.ManyToManyField(blank=True, related_name='translator_books', to='books.artists', verbose_name='Переводчики'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
